#!/usr/bin/make

APP_VERSION ?= 0.0.0

CC              := musl-gcc
C_SIZE_FLAGS     = -Os -ffunction-sections -fdata-sections
C_SECURITY_FLAGS = -fstack-protector-strong -D_FORTIFY_SOURCE=2
C_WARNING_FLAGS  = -Wall -Wextra -Werror -Wpedantic -Wformat=2 -Wformat-security -Wnull-dereference \
	-Wstack-protector -Wstrict-overflow=3 -Wwrite-strings -Wconversion -Wshadow
C_STRIP_FLAGS    = -s -fno-asynchronous-unwind-tables -fno-ident -Wl,--build-id=none
C_LDFLAGS        = -static -Wl,--gc-sections
CFLAGS           = $(C_SIZE_FLAGS) $(C_SECURITY_FLAGS) $(C_WARNING_FLAGS) $(C_STRIP_FLAGS) $(C_LDFLAGS)
STRIP_FLAGS      = -s -R .comment -R .gnu.version -R .note -R .note.ABI-tag

.PHONY: src/version.h clean

.DEFAULT_GOAL: all
all: httpcheck httpscheck portcheck parallel pidcheck

libs/mbedtls4:
	CC=$(CC) $(MAKE) -C ./libs mbedtls4

src/modules/obj/cli.o: src/modules/cli/cli.c src/modules/cli/cli.h
	$(CC) -c $(CFLAGS) -o $@ $<

src/modules/bin/cli_test: src/modules/cli/cli_test.c src/modules/obj/cli.o
	$(CC) $(CFLAGS) -o $@ $< src/modules/obj/cli.o

httpcheck: src/httpcheck.c src/version.h
	$(CC) $(CFLAGS) -o $@ $<
	strip $(STRIP_FLAGS) $@

httpscheck: src/httpcheck.c src/version.h libs/mbedtls4
	$(CC) $(CFLAGS) -DWITH_TLS \
		-Ilibs/mbedtls4/include \
		-Ilibs/mbedtls4/tf-psa-crypto/include \
		-Ilibs/mbedtls4/tf-psa-crypto/drivers/builtin/include \
		-Llibs/mbedtls4/build/library \
		-o $@ $< \
		-lmbedtls -lmbedx509 -ltfpsacrypto
	strip $(STRIP_FLAGS) $@

portcheck: src/portcheck.c src/version.h
	$(CC) $(CFLAGS) -o $@ $<
	strip $(STRIP_FLAGS) $@

parallel: src/parallel.c src/version.h
	$(CC) $(CFLAGS) -o $@ $<
	strip $(STRIP_FLAGS) $@

pidcheck: src/pidcheck.c src/version.h
	$(CC) $(CFLAGS) -o $@ $<
	strip $(STRIP_FLAGS) $@

.PHONY: src/version.h
src/version.h:
	@printf '// Code generated by `make`; DO NOT EDIT.\n\n#ifndef VERSION_H\n#define VERSION_H\n#define APP_VERSION "%s"\n#endif\n' "$(APP_VERSION)" > $@

SRC_FILES := $(shell find src -type f \( -name '*.c' -o -name '*.h' \))

fmt: $(SRC_FILES)
	clang-format -i $^

test: httpcheck httpscheck parallel pidcheck
	python3 ./test/httpcheck.py --bin ./httpcheck
	python3 ./test/httpcheck.py --bin ./httpscheck --https
	python3 ./test/httpcheck.py --bin ./httpscheck
	python3 ./test/parallel.py --bin ./parallel
	python3 ./test/pidcheck.py --bin ./pidcheck

.PHONY: clean
clean:
	-rm ./cli_test ./httpcheck ./httpscheck ./portcheck ./parallel ./pidcheck
